apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: antiintuit
spec:
  clusterIP: None
  selector:
    app: antiintuit-mariadb
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306