apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-data
  namespace: antiintuit
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi