apiVersion: v1
kind: Service
metadata:
  name: session-manager
  namespace: antiintuit
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: session-queue
  ports:
    - port: 26960
      targetPort: 26960