apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: antiintuit-questions-unlocker
  namespace: antiintuit
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            work: questions-unlocker
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
          containers:
            - name: antiintuit-questions-unlocker
              image: maxsid/antiintuit
              command:
                - python
                - -c
                - from antiintuit.database import Question; Question.unlock_all_questions(40)
              envFrom:
                - prefix: GRAYLOG_
                  configMapRef:
                    name: graylog-config
              env:
                - name: CONFIG_DIRECTORIES
                  value: /sec
              volumeMounts:
                - mountPath: /sec
                  name: database-secret
                  readOnly: true
          imagePullSecrets:
            - name: maxsid-docker-hub
          volumes:
            - name: database-secret
              secret:
                secretName: database-secret