apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: anitiintuit-tests-solver
  namespace: antiintuit
spec:
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 2100
      parallelism: 3
      template:
        metadata:
          labels:
            work: tests_solver
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
          containers:
            - name: anitiintuit-tests-solver
              image: maxsid/antiintuit
              command:
                - python
                - -c
                - from antiintuit.jobs.tests_solver import run_job; run_job()
              envFrom:
                - prefix: GRAYLOG_
                  configMapRef:
                    name: graylog-config
              env:
                - name: STATIC_DIRECTORY
                  value: /static-data
                - name: INTUIT_SSL_VERIFY
                  value: "false"
                - name: CONFIG_DIRECTORIES
                  value: /sec
                - name: TEST_SOLVER_SESSION_QUEUE_HOST
                  value: session-queue-0.session-manager.antiintuit.svc.cluster.local
              volumeMounts:
                - mountPath: /sec
                  name: database-secret
                  readOnly: true
                - mountPath: /static-data
                  name: static-data
          imagePullSecrets:
            - name: maxsid-docker-hub
          volumes:
            - name: database-secret
              secret:
                secretName: database-secret
            - name: static-data
              persistentVolumeClaim:
                claimName: static-data
