apiVersion: batch/v1
kind: Job
metadata:
  name: antiintuit-database-tables-init
  namespace: antiintuit
spec:
  template:
    metadata:
      labels:
        work: init-database
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
      containers:
        - name: antiintuit-database-tables-init
          image: maxsid/antiintuit
          command:
            - python
            - -c
            - from antiintuit.database import create_tables; create_tables()
          envFrom:
            - prefix: GRAYLOG_
              configMapRef:
                name: graylog-config
          env:
            - name: CONFIG_DIRECTORIES
              value: /sec
          volumeMounts:
            - mountPath: /sec
              name: database-secret
              readOnly: true
      imagePullSecrets:
        - name: maxsid-docker-hub
      volumes:
        - name: database-secret
          secret:
            secretName: database-secret
