apiVersion: v1
kind: Service
metadata:
  name: tbot-redis
  namespace: antiintuit
  labels:
    service: tbot
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: tbot-redis