apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tbot-redis
  namespace: antiintuit
  labels:
    service: tbot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi