apiVersion: v1
kind: Service
metadata:
  name: antiintuit-json-api
  namespace: antiintuit
spec:
  clusterIP: None
  selector:
    app: antiintuit-json-api
  ports:
    - port: 5000
      targetPort: 5000